# Generated by Django 3.2 on 2021-11-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCompra', '0005_auto_20211102_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
